# mPaaS Pods Begin
plugin "cocoapods-mPaaS"
source "https://code.aliyun.com/mpaas-public/podspecs.git"
#use_pod_for_mPaaS!
mPaaS_baseline '10.1.60'  # 请将 x.x.x 替换成真实基线版本
mPaaS_version_code 38   # This line is maintained by MPaaS plugin automatically. Please don't modify.
# mPaaS Pods End

platform :ios, '9.0'

target 'MPTinyAppDemo_pod' do

  mPaaS_pod "mPaaS_TinyApp"

  mPaaS_pod "mPaaS_Share"
  
  mPaaS_pod "mPaaS_AliAccount"

end
